#ifndef _BSP_H
#define _BSP_H

#include "main.h"

#define 	L_CTL_PIN			GPIO_PIN_4
#define		L_CTL_PORT			GPIOC

#define 	N_CTL_PIN			GPIO_PIN_5
#define		N_CTL_PORT			GPIOC

#define		LEDB_PIN			GPIO_PIN_11
#define		LEDB_PORT			GPIOC

#define		LEDG_PIN			GPIO_PIN_10
#define		LEDG_PORT			GPIOC

#define		LEDR1_PIN			GPIO_PIN_12
#define		LEDR1_PORT			GPIOC

#define		LEDR2_PIN			GPIO_PIN_2
#define		LEDR2_PORT			GPIOD


#define		ENERGY_INT1_PIN		GPIO_PIN_8
#define		ENERGY_INT1_PORT	GPIOA

#define		ENERGY_INT2_PIN		GPIO_PIN_11
#define		ENERGY_INT2_PORT	GPIOA

#define 	EARTH_ACT_PIN		GPIO_PIN_12
#define		EARTH_ACT_PORT		GPIOA

#define 	LEDB_ON				HAL_GPIO_WritePin(LEDB_PORT,LEDB_PIN,GPIO_PIN_SET)
#define 	LEDB_OFF			HAL_GPIO_WritePin(LEDB_PORT,LEDB_PIN,GPIO_PIN_CLEAR)

#define 	LEDG_ON				HAL_GPIO_WritePin(LEDG_PORT,LEDG_PIN,GPIO_PIN_SET)
#define 	LEDG_OFF			HAL_GPIO_WritePin(LEDG_PORT,LEDG_PIN,GPIO_PIN_CLEAR)

#define 	LEDR1_ON			HAL_GPIO_WritePin(LEDR1_PORT,LEDR1_PIN,GPIO_PIN_SET)
#define 	LEDR1_OFF			HAL_GPIO_WritePin(LEDR1_PORT,LEDR1_PIN,GPIO_PIN_CLEAR)

#define 	LEDR2_ON			HAL_GPIO_WritePin(LEDR2_PORT,LEDR2_PIN,GPIO_PIN_SET)
#define 	LEDR2_OFF			HAL_GPIO_WritePin(LEDR2_PORT,LEDR2_PIN,GPIO_PIN_CLEAR)

#define		LN_CTL_ON			HAL_GPIO_WritePin(GPIOC,GPIO_PIN_4|GPIO_PIN_5,GPIO_PIN_SET)
#define		LN_CTL_OFF			HAL_GPIO_WritePin(GPIOC,GPIO_PIN_4|GPIO_PIN_5,GPIO_PIN_CLEAR)

//#define		READ_EARTH			((GPIOAB->IDATA) & EARTH_ACT_PIN)	//HAL_GPIO_ReadPin(EARTH_ACT_PORT,EARTH_ACT_PIN)


void bsp_init(void);


	
#endif 



